shapeless-recipes:
- BOW = BOW + STRING
- FISHING_ROD = FISHING_ROD + STRING
- WOOD_PICKAXE = WOOD_PICKAXE + WOOD
- WOOD_SWORD = WOOD_SWORD + WOOD
- WOOD_SPADE = WOOD_SPADE + WOOD
- WOOD_HOE = WOOD_HOE + WOOD
- WOOD_AXE = WOOD_AXE + WOOD
- STONE_PICKAXE = STONE_PICKAXE + COBBLESTONE
- STONE_SWORD = STONE_SWORD + COBBLESTONE
- STONE_SPADE = STONE_SPADE + COBBLESTONE
- STONE_HOE = STONE_HOE + COBBLESTONE
- STONE_AXE = STONE_AXE + COBBLESTONE
- IRON_PICKAXE = IRON_PICKAXE + IRON_INGOT
- IRON_SWORD = IRON_SWORD + IRON_INGOT
- IRON_SPADE = IRON_SPADE + IRON_INGOT
- IRON_HOE = IRON_HOE + IRON_INGOT
- IRON_AXE = IRON_AXE + IRON_INGOT
- GOLD_PICKAXE = GOLD_PICKAXE + GOLD_INGOT
- GOLD_SWORD = GOLD_SWORD + GOLD_INGOT
- GOLD_SPADE = GOLD_SPADE + GOLD_INGOT
- GOLD_HOE = GOLD_HOE + GOLD_INGOT
- GOLD_AXE = GOLD_AXE + GOLD_INGOT
- DIAMOND_PICKAXE = DIAMOND_PICKAXE + DIAMOND
- DIAMOND_SWORD = DIAMOND_SWORD + DIAMOND
- DIAMOND_SPADE = DIAMOND_SPADE + DIAMOND
- DIAMOND_HOE = DIAMOND_HOE + DIAMOND
- DIAMOND_AXE = DIAMOND_AXE + DIAMOND
- LEATHER_HELMET = LEATHER_HELMET + LEATHER
- LEATHER_CHESTPLATE = LEATHER_CHESTPLATE + LEATHER
- LEATHER_LEGGINGS = LEATHER_LEGGINGS + LEATHER
- LEATHER_BOOTS = LEATHER_BOOTS + LEATHER
- IRON_HELMET = IRON_HELMET + IRON_INGOT
- IRON_CHESTPLATE = IRON_CHESTPLATE + IRON_INGOT
- IRON_LEGGINGS = IRON_LEGGINGS + IRON_INGOT
- IRON_BOOTS = IRON_BOOTS + IRON_INGOT
- GOLD_HELMET = GOLD_HELMET + GOLD_INGOT
- GOLD_CHESTPLATE = GOLD_CHESTPLATE + GOLD_INGOT
- GOLD_LEGGINGS = GOLD_LEGGINGS + GOLD_INGOT
- GOLD_BOOTS = GOLD_BOOTS + GOLD_INGOT
- DIAMOND_HELMET = DIAMOND_HELMET + DIAMOND
- DIAMOND_CHESTPLATE = DIAMOND_CHESTPLATE + DIAMOND
- DIAMOND_LEGGINGS = DIAMOND_LEGGINGS + DIAMOND
- DIAMOND_BOOTS = DIAMOND_BOOTS + DIAMOND
